### ISSUE TITLE
Support for WebdriverIO version 5

### ISSUE THREAD

**Issue by ilan-klinghofer** [ng-apimock/webdriverio-plugin#2]
We are trying to use this plugin in our project that uses webdriverio 5.10.1.

It appears that there are some breaking changes in webdriver 5, including setCookie no longer available.

see https://github.com/webdriverio/webdriverio/blob/master/CHANGELOG.md#v500-2018-12-20

**Comment by mdasberg** [comment]
@ilan-klinghofer thanks for reporting the issue.

I will make a fix for this asap.

**Comment by mdasberg** [comment]
@ilan-klinghofer I have just released version 2.0.0
It is now complient with the [custom wdio service ](https://webdriver.io/docs/customservices.html) setup.

If you run into any issue, please let me know.
