### ISSUE TITLE
How to use with WebdriverIO 6

### ISSUE THREAD

**Issue by DaveGold** [ng-apimock/webdriverio-plugin#4]
I tried to update to WebdriverIO 6 but i get errors:

ERROR @wdio/sync: ReferenceError: client is not defined
ERROR @wdio/sync: TypeError: Url must be a string. Received undefined

I have this configured:

services: ['selenium-standalone', ['ng-apimock', { globalName: 'client' }]],

Somehow the client is not defined anymore.

**Comment by mdasberg** [comment]
@DaveGold the baseUrl is no longer available as an option. Instead is is available on the browser.config object.

I will try to make a release tomorrow

**Comment by DaveGold** [comment]
Hi, I see you added a commit. will this be released in newer version?

**Comment by mdasberg** [comment]
@DaveGold v2.0.3 has been released.

**Comment by mdasberg** [comment]
@DaveGold please let me know if this solves the problem.

Integration tests are now executed against webdriverio v5 and v6 (https://github.com/ng-apimock/webdriverio-plugin/runs/785570657?check_suite_focus=true)

**Comment by DaveGold** [comment]
@mdasberg I will try this out soon

**Comment by DaveGold** [comment]
@mdasberg  I can confirm it works with Webdriver6
